### ISSUE TITLE
Better error messages when trying to generate graph data from a tabular pipeline etc...

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/lein-grafter#3]
e.g.

``` clojure
10:54 $ lein grafter run foobarbaz.pipeline/convert-persons-data ./data/example-data.csv example-output.ttl
(:repositories detected in user-level profiles! [:swirrl-private-repos]
See https://github.com/technomancy/leiningen/wiki/Repeatability)
./data/example-data.csv --[foobarbaz.pipeline/convert-persons-data]--> example-output.ttl
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :->sesame-rdf-type of protocol: #'grafter.rdf.io/ISesameRDFConverter found for class: clojure.lang.MapEntry, compiling:(/private/var/folders/6j/vpfh3hk97mq82r9nmq7d2h0h0000gn/T/form-init268606107216153921.clj:1:124)
    at clojure.lang.Compiler.load(Compiler.java:7391)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj:277)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj:339)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj:384)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :->sesame-rdf-type of protocol: #'grafter.rdf.io/ISesameRDFConverter found for class: clojure.lang.MapEntry
    at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
    at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:560)
    at grafter.rdf.io$eval9934$fn__9935$G__9923__9940.invoke(io.clj:44)
    at grafter.rdf.io$eval10185$fn__10186.invoke(io.clj:411)
    at grafter.rdf.protocols$eval8690$fn__8691$G__8679__8704.invoke(protocols.clj:11)
    at grafter.rdf.io$eval10185$fn__10188.invoke(io.clj:419)
    at grafter.rdf.protocols$eval8690$fn__8712$G__8681__8743.invoke(protocols.clj:11)
    at grafter.rdf$add.invokeStatic(rdf.clj:84)
    at grafter.rdf$add.invoke(rdf.clj:76)
    at user$eval12316.invokeStatic(form-init268606107216153921.clj:1)
    at user$eval12316.invoke(form-init268606107216153921.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.eval(Compiler.java:6917)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    ... 14 more
Subprocess failed
```

We should also display a better error if you do it the other way - and try and generate a tabular file from graph data.

**Comment by RickMoynihan** [comment]
Also should display better errors when you [reference a pipeline that doesn't exist](https://github.com/Swirrl/grafter/issues/81)
